### PR TITLE
operating-system: Fully rely on Python to determine path separator

### PR DESCRIPTION
**Pull request by maxbrunet**

### CODE REVIEW

**Comment by maxbrunet** [comment]
Hey @brikis98, I was passing by, I thought I'd be a little nicer, just a random contribution, please feel free to do whatever you like with it.

**Comment by brikis98** [comment]
Ah, gotcha. OK, so just to sanity check, you didn't hit a bug with the original version, did you?

**Comment by brikis98** [comment]
(BTW, I just kicked off the tests)

**Comment by maxbrunet** [comment]
No, no bug found 🙂

**Comment by brikis98** [comment]
Roger! Tests passed, so I'll merge now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/package-terraform-utilities/releases/tag/v0.1.7

**Pull request merged**
